"""rename address

Revision ID: 1bd28f5b1c7d
Revises: 855633e3069b
Create Date: 2024-02-27 10:12:21.398788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd28f5b1c7d'
down_revision = '855633e3069b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',
new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',
new_column_name='address')
    # ### end Alembic commands ###
