"""add Department

Revision ID: 855633e3069b
Revises: 3c43e092efc0
Create Date: 2024-02-27 10:01:43.854453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855633e3069b'
down_revision = '3c43e092efc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.Integer(), nullable=True))
    op.drop_column('departments', 'salary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('salary', sa.INTEGER(), nullable=True))
    op.drop_column('departments', 'address')
    # ### end Alembic commands ###
